### ISSUE TITLE
Build Failed: Couldn't get dependency '//jsc:jscoffsetextractor#android-x86,static'

### ISSUE THREAD

**Issue by bsansouci** [facebook/android-jsc#6]
I'm probably doing something weird, but when I run `buck build :android-jsc` I get the following errors
```
BUILD FAILED: Couldn't get dependency '//jsc:jscoffsetextractor#android-x86,static' of target '//jsc:LLIntAssembly.android-x86.h':
Unrecognized flavor in target //jsc:jscoffsetextractor#android-x86,static while parsing //jsc/BUCK.
```

Any ideas? Thanks :)

**Comment by kmagiera** [comment]
You probably don't have android NDK setup correctly. Do you have $ANDROID_NDK or $ANDROID_NDK_REPOSITORY set in you shell?

**Comment by bsansouci** [comment]
I have `$ANDROID_NDK` set to `/usr/local/opt/android-ndk-r10e`

**Comment by kmagiera** [comment]
@bsansouci  Are you still experiencing this issue?

**Comment by bsansouci** [comment]
Nope, I think I set up the android-sdk wrong. I ran android studio on another project and told me it could fix my setup. After that everything worked. Thanks!

**Comment by leeight** [comment]
@kmagiera I set up the `ANDROID_NDK` and `ANDROID_HOME` environment

```
export ANDROID_NDK=$HOME/local/dev/android-ndk-r10e
export ANDROID_HOME=$HOME/local/dev/android-sdk
```

But get the following build errors

```
BUILD FAILED: Couldn't get dependency '//jsc:jscoffsetextractor#android-armv7,static' of target '//jsc:LLIntAssembly.android-armv7.h':
Unrecognized flavor in target //jsc:jscoffsetextractor#android-armv7,static while parsing //jsc/BUCK
Here are some things you can try to get the following flavors to work::
android-armv7 : Make sure you have the Android SDK/NDK installed and set up. See https://buckbuild.com/setup/install.html#locate-android-sdk
```

---

I check the `./jsc/extra_headers/LLIntAssembly.h` file, it looks like `LLIntAssembly.android-armv7.h` and `LLIntAssembly.android-x86.h` not exists in the repos? Do them are auto generated?

**Comment by leeight** [comment]
I found the reason. In the `.buckconfig` file, the `ndk_version` was set to `r10c`, but my installed ndk version is `r10e`.

I update the `.buckconfig` and set to the correct version, then everything works well.

**Comment by slimeygecko** [comment]
I'm having the same issue.. my SDK and NDK are set correctly, I updated my `.buckconfig` file to reflect the version of NDK that I have (`r13b`), but I still get the same error, suggesting that I need to install the SDK/NDK. Any ideas?
